### ISSUE TITLE
AttributeError: traincsv

### ISSUE THREAD

**Issue by trikim** [MasazI/InceptionV3_TensorFlow#4]
when I run "python trainer.py", I encountered the error. my tensorflow version is 1.4.0-dev20170920.
Traceback (most recent call last):
  File "trainer.py", line 218, in <module>
    tf.app.run()
  File "/home/care/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "trainer.py", line 214, in main
    train()
  File "trainer.py", line 26, in train
    print("The number of training images is: %d" % (dataset.cnt_samples(FLAGS.traincsv)))
  File "/home/care/.local/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 58, in __getattr__
    raise AttributeError(name)
AttributeError: traincsv
Could you tell me how to deal with this problem?

**Comment by AnupriyaJaju** [comment]
I am also having this same exact error and have no idea how to deal with it. Can you please update here about how to solve this issue.

**Comment by 0Deer0** [comment]
I found a solution. You can modify the settings.py file. Replace the 'tfcsv' by 'traincsv'. Then this problem is fixed.
